# Generated by Django 3.1.4 on 2021-01-04 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210104_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
