# Generated by Django 3.1.4 on 2021-01-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
