# Generated by Django 3.1.4 on 2021-01-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210104_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
