# Generated by Django 3.1.4 on 2021-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210104_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
