# Generated by Django 3.1.4 on 2021-01-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210104_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.city'),
        ),
    ]
