# Generated by Django 3.1.4 on 2021-01-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20210105_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
