# Generated by Django 3.1.4 on 2021-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20210106_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='views',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
