# Generated by Django 3.1.4 on 2021-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_auto_20210108_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
