# Generated by Django 3.1.5 on 2021-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='private',
        ),
        migrations.RemoveField(
            model_name='room',
            name='public',
        ),
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
