# Generated by Django 3.1.5 on 2021-01-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_auto_20210114_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_enquiry',
            field=models.IntegerField(default=0),
        ),
    ]
