# Generated by Django 3.1.5 on 2021-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_room_total_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='feature_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
