# Generated by Django 3.1.5 on 2021-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_auto_20210118_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='featured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
