# Generated by Django 3.1.5 on 2021-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0027_room_featured_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='feature_request',
        ),
        migrations.AlterField(
            model_name='room',
            name='featured',
            field=models.CharField(choices=[('not_featured', 'Not Featured'), ('featured', 'Featured'), ('feature_request', 'Featured_Request')], default='not_featured', max_length=100),
        ),
    ]
