# Generated by Django 3.1.5 on 2021-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_room_times_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='feature_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='featured',
            field=models.CharField(choices=[('not_featured', 'Not Featured'), ('featured', 'Featured'), ('feature_request', 'Featured Request'), ('denied', 'Featured Denied')], default='not_featured', max_length=100),
        ),
    ]
