# Generated by Django 3.1.5 on 2021-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0031_room_day_remaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='day_remaning',
            field=models.DateField(blank=True, null=True),
        ),
    ]
