# Generated by Django 3.1.5 on 2021-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0033_auto_20210118_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='day_remaning',
            field=models.DateField(default=0),
        ),
    ]
