# Generated by Django 3.1.5 on 2021-01-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0034_auto_20210119_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='day_remaning',
        ),
    ]
