# Generated by Django 3.1.5 on 2021-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0035_remove_room_day_remaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='day_remaning',
            field=models.IntegerField(default=0),
        ),
    ]
