# Generated by Django 3.1.5 on 2021-01-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0041_auto_20210124_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='bedroom',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='c_parking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='day_remaning',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='parking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='times_featured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_enquiry',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_report',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
