# Generated by Django 3.1.5 on 2021-01-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0042_auto_20210125_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='kitchen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
