# Generated by Django 3.1.5 on 2021-01-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_enquiry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='user',
        ),
    ]
