# Generated by Django 3.1.5 on 2021-01-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0022_auto_20210113_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fake_contact', 'Fake Contact'), ('fake_room', 'Fake Room'), ('misleading', 'Misleading Description'), ('other', 'Other')], default='fake_contact', max_length=20)),
                ('report_description', models.TextField(default='Descripe complaint')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
