# Generated by Django 3.1.4 on 2021-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='room_tag',
            field=models.IntegerField(unique=True),
        ),
    ]
