# Generated by Django 3.1.5 on 2021-01-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210114_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_enquiry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
